name: Manually build deb package with Docker image

on:
  push:
    branches: [ Debian ]
  pull_request:
    branches: [ Debian ]
  workflow_dispatch:

jobs:
  build:
    runs-on: debian-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and deploy
      run: ./build.sh

    - name: Archive artifacs
      uses: actions/upload-artifact@v3
      with:
        name: emacs-gcc-pgtk
        path: ./deploy/emacs-gcc-pgtk_*.deb
